---
- hosts: db
  become: yes
  ignore_errors: yes
  gather_facts: true
  vars: 
   color: red

  tasks:
    - name: Check the number of CPUs
      command: uptime
      register: nproc_output

    - name: Display the CPU count
      debug:
        var: nproc_output.stdout

    - name: Create a file
      file:
        path: /home/ec2-user/week3
        state: touch
        mode: '0644'
      register: file_output

    - name: Display file creation output
      debug:
        var: color

